version: '3.9'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgresql
      - POSTGRES_DB=tasks-management