service: task-manager-lambda

plugins:
  - serverless-python-requirements
  - serverless-plugin-scripts
  - serverless-wsgi

functions:
  - app:
      handler: wsgi_handler.handler
      events:
        - http: ANY /
        - http: ANY /{proxy+}
      timeout: 30

package:
  patterns:
    - '!.flake8'
    - '!.github/**'
    - '!.pytest_cache/**'
    - '!dist/**'
    - '!node_modules/**'
    - '!package-lock.json'
    - '!package.json'
    - '!tests/**'

custom:
  stage: ${env:STAGE}
  wsgi:
    app: amanager.wsgi.application

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2
  stage: ${env:stage}

  vpc:
    securityGroupIds:
      - <your-security-group-id>
      - <your-security-group-id>
    subnetIds:
      - <your-subnet-id>
      - <your-subnet-id>
    
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
