service: signol-shameen-dev
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: '${opt:stage, "dev"}'
  environment:
    NODE_ENV: ${self:provider.stage}
    ENV: ${self:provider.stage}
    PGHOST: ${env:PGHOST}
    PGPORT: ${env:PGPORT}
    PGUSER: ${env:PGUSER}
    PGPASSWORD: ${env:PGPASSWORD}
    PGDATABASE: ${env:PGDATABASE}
    PGSSLMODE: ${env:PGSSLMODE}

package:
  include:
    - .env.dev
    - .env.production

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createMany:
    handler: app/handler.createMany
    description: (Signol Shameen) Create Many Tasks
    events:
      - http:
          path: tasks
          method: post
  update:
    handler: app/handler.update
    description: (Signol Shameen) Update Task Status
    events:
      - http:
          path: tasks/{id}
          method: put
  find:
    handler: app/handler.find
    description: (Signol Shameen) Get All Tasks
    events:
      - http:
          path: tasks
          method: get
