service: signol-shameen-dev

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true
package:
  include:
    - .env

functions:
  createMany:
    handler: app/handler.createMany
    events:
      - http:
          path: tasks
          method: post
  update:
    handler: app/handler.update
    events:
      - http:
          path: tasks/{id}
          method: put
  find:
    handler: app/handler.find
    events:
      - http:
          path: tasks
          method: get
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: tasks/{id}
          method: get
