service: signol-tech-test-backend-api

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: signol-tech-test-backend-api-layer
      description: Signol tech test backend API layer
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      include:
        - "src/**"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".venv/**"
        - "node_modules/**"

    handler: src.api.handler
    environment:
      STAGE: ${self:provider.stage}
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_DATABASE_NAME: ${env:DB_DATABASE_NAME}
      DB_USER: ${env:DB_USER}
      DB_PASSWORD: ${env:DB_PASSWORD}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
