# Generated by Django 4.1.6 on 2023-02-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=55, verbose_name="owner")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "company_name",
                    models.CharField(max_length=55, verbose_name="company_name"),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(max_length=1000)),
                ("status", models.CharField(default="IR", max_length=2)),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": "tasks",
            },
        ),
    ]
