# Generated by Django 4.1.5 on 2023-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('created_by', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('completed_by', models.DateTimeField(blank=True)),
                ('company', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Review', 'Review')], default='Review', max_length=255)),
            ],
        ),
    ]
