# Generated by Django 4.1.5 on 2023-01-31 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
