# Generated by Django 4.1.5 on 2023-01-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Approved', '0'), ('Rejected', '1'), ('Review', '2')], default='2', max_length=255),
        ),
    ]
