# Generated by Django 4.1.5 on 2023-01-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0 Approved', 'Approved'), ('1 Rejected', 'Rejected'), ('2 Review', 'Review')], default='2', max_length=255),
        ),
    ]
