# Generated by Django 4.1.5 on 2023-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='2', max_length=255),
        ),
    ]
