# The name of the action
name: Check
# When the action is triggered
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  build:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run test suite
      - name: Test
        run: pytest -vv
      
      # Run linter
      - name: Lint
        run: flake8
