name: Deploy Backend (Serverless)
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install --frozen-lockfile
        working-directory: ./server

      - name: serverless deploy
        uses: serverless/github-action@v3.1
        working-directory: ./server
        with:
          args: deploy
        env:
          #SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
